export const state = {
    selectedVersion: "4.3",
    sortMode: "relevance",
    showOlderVersions: false,
    searchText: "",
    page: 1,
    pageSize: 30,
    totalPages: 1,
    isLoading: false,
    selectedTab: "version",
    settingsTab: "general",
    downloadEventUnsubscribe: null,
    searchDebounceHandle: null,
    versionLoadingDelayHandle: null,
    versionSkeletonVisible: false,
    versionRequestSeq: 0,
    activeDetailWorkshopId: null,
    activeCards: [],
    settingsModel: null,
    settingsDirty: false,
    windowClosePromptActive: false,
    windowCloseAllowed: false,
    usernamePromptShown: false,
    gameRunning: false,
    gamePollingHandle: null,
    stellarisyncPollingHandle: null,
    modsPathMigrationPollingHandle: null,
    mergerProgressPollingHandle: null,
    modsPathMigration: {
        active: false,
        sourceModsPath: null,
        targetModsPath: null,
        moveExistingMods: false,
        startedAtUtc: null,
        completedAtUtc: null,
        lastMessage: null,
        currentModName: null,
        currentPhase: null,
        processedModCount: 0,
        totalModCount: 0,
        progressPercent: 0,
        modalVisible: false,
        backgrounded: false,
        pendingPromise: null
    },
    workshopMouseNavHooked: false,
    workshopReturnContext: null,
    tabHistory: [],
    tabForwardStack: [],
    queueHadActiveWork: false,
    queueRowsByWorkshopId: new Map(),
    queueSnapshot: null,
    queueLibrarySyncKey: "",
    queueLibrarySyncInFlight: false,
    downloadFailureNotice: {
        latestFailureKey: "",
        dismissedFailureKey: "",
        workshopId: null,
        modName: null,
        message: "",
        updatedAtUtc: null
    },
    library: {
        snapshot: null,
        searchText: "",
        showEnabledOnly: false,
        selectedModId: null,
        removingModIds: new Set(),
        dragSourceModId: null,
        descriptorTagsExpanded: false,
        availableTags: [],
        selectedReportTags: [],
        savedReportTagsByModVersion: {}
    },
    merger: {
        plan: null,
        summary: null,
        selectedVirtualPath: null,
        resultsFilter: "needs-action",
        resultsMode: "review",
        previewCache: new Map(),
        previewLoadingKey: null,
        previewSelectedModId: null,
        lastBuildOutputPath: null,
        lastReportPath: null,
        progress: {
            active: false,
            operation: null,
            startedAtUtc: null,
            completedAtUtc: null,
            phase: null,
            currentItemLabel: null,
            processedItemCount: 0,
            totalItemCount: 0,
            progressPercent: 0,
            message: null,
            lastResultOk: null,
            modalVisible: false,
            backgrounded: false
        }
    }
};
